name: Flutter CI CD by Adawy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter version 3.29.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Build APK release
        run: flutter build apk --release

      - name: Build AppBundle release
        run: flutter build appbundle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AppBundle
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle-${{ github.run_number }}
          path: build/app/outputs/bundle/release/app-release.aab


      # - name: Upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.APP_ID}} 
      #     serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      #     groups: testers
      #     file: build/app/outputs/flutter-apk/app-release.apk
