name: Flutter CI CD by Adawy

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter version 3.29.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name:
        run: flutter test

      # - name: Build APK release
      #   run: flutter build apk --release

      # - name: Build AppBundle release
      #   run: flutter build appbundle
      
      - name: Build ios release
        run: flutter build ios --release --no-codesign

      # - name: Upload Apk
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release-apk-${{ github.run_number }}
      #     path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Upload Appbundle
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release-appbundle-${{ github.run_number }}
      #     path: build/app/outputs/bundle/release/app-release.aab

      - name: Archive .app to .ipa
        run: |
          mkdir -p build/ios/ipa
          xcrun xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist || true

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/
          
      # - name: Upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.APP_ID}}
      #     serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      #     groups: testers
      #     file: build/app/outputs/flutter-apk/app-release.apk

  # deploy-web:
  #   name: Deploy to Firebase
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #     - run: flutter pub get
  #     - run: flutter build web --release
  #     - uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
  #         projectId: your-project-id
  #         channelId: live

  # deploy-ios:
  #   name: Deploy to App Store
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.1.2'
  #     - run: gem install fastlane -NV
  #     - run: fastlane deploy_to_appstore

  # deploy-android:
  #   name: Deploy to Google Play Store
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.1.2'
  #     - run: gem install fastlane -NV
  #     - run: fastlane supply --aab $(find . -name "*.aab") --track internal --json_key "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}"